data_local: ./my-copy-c4
data_remote: # If blank, files must be present in data_local
max_seq_len: 128
global_seed: 17

# Run Name
run_name: mpt_causal_lm_cpu # If left blank, will be read from env var $RUN_NAME

# Model
model:
  name: mpt_causal_lm
  init_device: cpu
  d_model: 16
  n_heads: 4
  n_layers: 4
  expansion_ratio: 5
  max_seq_len: ${max_seq_len}
  vocab_size: 50368
  attn_config:
    attn_impl: torch
  loss_fn: torch_crossentropy

# Tokenizer
tokenizer:
  name: EleutherAI/gpt-neox-20b
  kwargs:
    model_max_length: ${max_seq_len}

# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
  drop_last: true
  num_workers: 2

eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    shuffle: false
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
  drop_last: false
  num_workers: 2

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 6.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 10ba
eval_interval: 5ba
eval_first: false
eval_subset_num_batches: 5
global_train_batch_size: 256
autoresume: false

# System
seed: ${global_seed}
device_eval_batch_size: 16
device_train_microbatch_size: 16
# device_train_microbatch_size: auto
precision: fp32

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: false

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

loggers:
  s3: {bucket_uri: s3://mosaicml-internal-checkpoints-shared/ }

# Profiler
profiler:
  sys_prof_cpu: false
  sys_prof_memory: false
  sys_prof_disk: false
  sys_prof_net: false
  sys_prof_stats_thread_interval_seconds: 1_000_000_000_000
  torch_prof_folder: '{run_name}/torch_traces'
  torch_prof_filename: 'rank{rank}.batch{batch}.pt.trace.json'
  torch_prof_remote_file_name:  'chuck/{run_name}/traces/ep{epoch}-ba{batch}-rank{rank}.json'
  torch_prof_overwrite: true
  torch_prof_use_gzip: false
  torch_prof_record_shapes: true
  torch_prof_profile_memory: true
  torch_prof_with_stack: true
  torch_prof_with_flops: true
  torch_prof_num_traces_to_keep: -1  # -1 means keep all traces
  schedule:
    skip_first: 1
    wait: 0
    warmup: 1
    active: 1
    repeat: 1
  # json_trace_handler:
  #   folder: '{run_name}/composer_traces'
  #   filename: 'ep{epoch}-ba{batch}-rank{rank}.json'
  #   remote_file_name: 's3://mosaicml-internal-checkpoints-shared/chuck/{run_name}/traces/ep{epoch}-ba{batch}-rank{rank}.json'
  #   merged_trace_filename: 'merged_trace.json'
  #   merged_trace_remote_file_name: '{run_name}/traces/merged_trace.json'
  #   overwrite: true
  #   num_traces_to_keep: -1

# Checkpoint to local filesystem or remote object store
# save_interval: 500ba
save_overwrite: true
save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
# save_folder: ./{run_name}/checkpoints
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints

# Load from local filesystem or remote object store
# load_path: ./gpt-125m/checkpoints/latest-rank{rank}.pt
# load_path: s3://my-bucket/my-folder/gpt-125m/checkpoints/latest-rank{rank}.pt
